---
apiVersion: v1
kind: Service
metadata:
  name: ldap-user-manager
  labels:
    app: ldap-user-manager
    chart: ldap-user-manager-v0.0.1
    release: ldap-user-manager
    heritage: Tiller
spec:
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: 443
      protocol: TCP
      name: https
  type: {{ .Values.service.type }}
  selector:
    app: ldap-user-manager
    release: ldap-user-manager
